### ISSUE TITLE
Can i use this code ?

### ISSUE THREAD

**Issue by shahid-pk** [awakecoding/CMakeSharp#1]
if this code is open source and you will allow.I will like to use it to contribute to dotnet coreclr project.

**Comment by awakecoding** [comment]
@shahid-pk if you see any value in it, sure, please go ahead. I just checked and .NET Core CLR is under the MIT license, so please consider that I am giving you a copy of the current repository under the MIT license.

**Comment by shahid-pk** [comment]
thanks alot
